require 'active_record'
require 'yaml'

task :default => :migrate

desc "Migrate the database through scripts in db/migrate. Target specific version with VERSION=x"
task :migrate => :environment do
    ActiveRecord::Migrator.migrate('db/migrate', ENV["VERSION"] ? ENV["VERSION"].to_i : nil )
end

task :fake_event => :environment do
  class ApiEvent < ActiveRecord::Base
  end
  x = 0
  while true
    ApiEvent.create!(:event => "{fake_event #{x}}")
    puts x
    if rand(50) == 0
      puts "sleep 1"
      sleep 1
    end
    x += 1

    puts Time.now if (x % 100) == 0
  end
end


task :environment do
    ActiveRecord::Base.establish_connection(YAML::load(File.open('database.yml')))
    ActiveRecord::Base.logger = Logger.new(File.open('database.log', 'a'))
end
